spring.application.name=microsservice-ticket
server.port=8081

# Configurações JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Configuração para usar banco de dados SQLite:
spring.datasource.url=jdbc:sqlite:ticket-db.sqlite
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
